const fs = require("fs");
const path = require("path");

const dbPath = path.join(__dirname, "database.json");

// 1. Elenco completo atualizado (com novos nomes mapeados)
const jogadores = [
  { id: "Neto", nome: "Neto", posicao: "Goleiro" },
  { id: "Raul", nome: "Raul", posicao: "Goleiro" },
  { id: "Léo_Linck", nome: "Léo Linck", posicao: "Goleiro" },
  { id: "Cristhian_Loor", nome: "Cristhian Loor", posicao: "Goleiro" },
  { id: "Rogério", nome: "Rogério", posicao: "Goleiro" },
  { id: "Alexander_Barboza", nome: "Alexander Barboza", posicao: "Defensor" },
  { id: "Bastos", nome: "Bastos", posicao: "Defensor" },
  { id: "Alex_Telles", nome: "Alex Telles", posicao: "Defensor" },
  { id: "Vitinho", nome: "Vitinho", posicao: "Defensor" },
  { id: "Mateo_Ponte", nome: "Mateo Ponte", posicao: "Defensor" },
  { id: "Ferraresi", nome: "Ferraresi", posicao: "Defensor" },
  { id: "Marçal", nome: "Marçal", posicao: "Defensor" },
  { id: "Kaio_Pantaleão", nome: "Kaio Pantaleão", posicao: "Defensor" },
  { id: "Justino", nome: "Justino", posicao: "Defensor" },
  { id: "Ythallo", nome: "Ythallo", posicao: "Defensor" },
  { id: "Lucas_Villalba", nome: "Lucas Villalba", posicao: "Defensor" },
  { id: "Jhoan_Hernández", nome: "Jhoan Hernández", posicao: "Defensor" },
  { id: "Kadu", nome: "Kadu", posicao: "Defensor" },
  { id: "Caio_Roque", nome: "Caio Roque", posicao: "Defensor" },
  { id: "Marquinhos", nome: "Marquinhos", posicao: "Defensor" },
  { id: "Caio_Valle", nome: "Caio Valle", posicao: "Defensor" },
  { id: "Allan", nome: "Allan", posicao: "Meio-campista" },
  { id: "Danilo", nome: "Danilo", posicao: "Meio-campista" },
  { id: "Cristian_Medina", nome: "Cristian Medina", posicao: "Meio-campista" },
  {
    id: "Santiago_Rodríguez",
    nome: "Santiago Rodríguez",
    posicao: "Meio-campista",
  },
  { id: "Edenílson", nome: "Edenílson", posicao: "Meio-campista" },
  { id: "Montoro", nome: "Montoro", posicao: "Meio-campista" },
  { id: "Newton", nome: "Newton", posicao: "Meio-campista" },
  { id: "Huguinho", nome: "Huguinho", posicao: "Meio-campista" },
  { id: "Wallace_Davi", nome: "Wallace Davi", posicao: "Meio-campista" },
  { id: "Jordan_Barrera", nome: "Jordan Barrera", posicao: "Meio-campista" },
  { id: "Bernardo_Valim", nome: "Bernardo Valim", posicao: "Meio-campista" },
  { id: "Felipe_Januário", nome: "Felipe Januário", posicao: "Meio-campista" },
  { id: "Arthur_Izaque", nome: "Arthur Izaque", posicao: "Meio-campista" },
  { id: "Lucas_Camilo", nome: "Lucas Camilo", posicao: "Meio-campista" },
  { id: "Matheusinho", nome: "Matheusinho", posicao: "Meio-campista" },
  { id: "Samuel_Alves", nome: "Samuel Alves", posicao: "Meio-campista" },
  { id: "Arthur_Novaes", nome: "Arthur Novaes", posicao: "Meio-campista" },
  { id: "Arthur_Cabral", nome: "Arthur Cabral", posicao: "Atacante" },
  { id: "Joaquín_Correa", nome: "Joaquín Correa", posicao: "Atacante" },
  { id: "Matheus_Martins", nome: "Matheus Martins", posicao: "Atacante" },
  { id: "Júnior_Santos", nome: "Júnior Santos", posicao: "Atacante" },
  { id: "Nathan_Fernandes", nome: "Nathan Fernandes", posicao: "Atacante" },
  { id: "Chris_Ramos", nome: "Chris Ramos", posicao: "Atacante" },
  { id: "Kadir_Barría", nome: "Kadir Barría", posicao: "Atacante" },
  { id: "Kauan_Toledo", nome: "Kauan Toledo", posicao: "Atacante" },
  { id: "Artur", nome: "Artur", posicao: "Atacante" },
  { id: "Gabriel_Abdias", nome: "Gabriel Abdias", posicao: "Atacante" },
  { id: "Matheus_Fortunato", nome: "Matheus Fortunato", posicao: "Atacante" },
  { id: "Rodrigo_Bellão", nome: "Rodrigo Bellão", posicao: "Treinador" },
  { id: "Martín_Anselmi", nome: "Martín Anselmi", posicao: "Treinador" },
  { id: "Franclim_Carvalho", nome: "Franclim Carvalho", posicao: "Treinador" },
];

// 2. Histórico de notas e partidas (Consolidado 2026-01 a 2026-05)
const historico = [
  {
    partida: "Portuguesa (F)",
    data: "15/01/2026",
    resultado: "2 x 1",
    Raul: 8.5,
    Kadu: 7.0,
    Danilo: 7.0,
    Justino: 7.0,
    Gabriel_Abdias: 6.5,
    Marquinhos: 6.0,
    Bernardo_Valim: 6.0,
    Caio_Valle: 7.5,
    Felipe_Januário: 7.0,
    Kauan_Toledo: 6.0,
    Arthur_Izaque: 5.5,
    Jordan_Barrera: 6.5,
    Matheus_Martins: 6.5,
    Mateo_Ponte: 6.0,
    Newton: 6.0,
    Lucas_Camilo: 7.5,
    Rodrigo_Bellão: 8.0,
  },
  {
    partida: "Sampaio Corrêa (F)",
    data: "18/01/2026",
    resultado: "2 x 1",
    Raul: 5.0,
    Rogério: 3.0,
    Danilo: 4.0,
    Justino: 5.5,
    Gabriel_Abdias: 5.0,
    Marquinhos: 5.0,
    Bernardo_Valim: 5.0,
    Caio_Valle: 6.0,
    Kauan_Toledo: 7.0,
    Felipe_Januário: 5.5,
    Arthur_Izaque: 6.0,
    Lucas_Camilo: 5.0,
    Matheus_Fortunato: 5.0,
    Matheusinho: 5.5,
    Samuel_Alves: 5.0,
    Rodrigo_Bellão: 5.5,
  },
  {
    partida: "Volta Redonda (C)",
    data: "21/01/2026",
    resultado: "1 x 0",
    Léo_Linck: 5.0,
    Mateo_Ponte: 5.5,
    Newton: 5.0,
    Alexander_Barboza: 6.0,
    Vitinho: 5.5,
    Allan: 5.0,
    Danilo: 6.0,
    Alex_Telles: 6.0,
    Artur: 6.0,
    Montoro: 8.5,
    Arthur_Cabral: 5.5,
    Santiago_Rodríguez: 7.5,
    Jordan_Barrera: 5.5,
    Matheus_Martins: 5.5,
    Nathan_Fernandes: 5.0,
    Marçal: 5.5,
    Martín_Anselmi: 6.0,
  },
  {
    partida: "Bangu (C)",
    data: "24/01/2026",
    resultado: "2 x 1",
    Neto: 6.5,
    Mateo_Ponte: 6.5,
    Newton: 6.5,
    Marçal: 6.5,
    Vitinho: 6.5,
    Allan: 6.0,
    Danilo: 7.0,
    Nathan_Fernandes: 6.0,
    Santiago_Rodríguez: 7.5,
    Montoro: 6.5,
    Arthur_Cabral: 6.0,
    Alex_Telles: 7.5,
    Jordan_Barrera: 5.5,
    Artur: 5.5,
    Matheus_Martins: 6.5,
    Alexander_Barboza: 6.0,
    Martín_Anselmi: 7.5,
  },
  {
    partida: "Cruzeiro (C)",
    data: "29/01/2026",
    resultado: "4 x 0",
    Neto: 7.5,
    Mateo_Ponte: 7.0,
    Newton: 7.5,
    Alexander_Barboza: 8.5,
    Vitinho: 8.0,
    Allan: 7.0,
    Danilo: 10.0,
    Alex_Telles: 7.5,
    Santiago_Rodríguez: 7.5,
    Montoro: 10.0,
    Arthur_Cabral: 8.0,
    Artur: 8.0,
    Matheus_Martins: 9.0,
    Marçal: 7.5,
    Nathan_Fernandes: 7.5,
    Martín_Anselmi: 9.0,
  },
  {
    partida: "Fluminense (F)",
    data: "01/02/2026",
    resultado: "2 x 1",
    Léo_Linck: 7.0,
    Mateo_Ponte: 6.5,
    Bastos: 6.0,
    Marçal: 6.5,
    Kadu: 5.5,
    Allan: 6.0,
    Jordan_Barrera: 5.0,
    Nathan_Fernandes: 5.0,
    Artur: 4.0,
    Matheus_Martins: 4.5,
    Kadir_Barría: 5.0,
    Vitinho: 5.5,
    Danilo: 6.0,
    Santiago_Rodríguez: 6.0,
    Montoro: 6.0,
    Alex_Telles: 5.5,
    Martín_Anselmi: 5.5,
  },
  {
    partida: "Grêmio (F)",
    data: "04/02/2026",
    resultado: "5 X 3",
    Neto: 1.5,
    Mateo_Ponte: 1.0,
    Newton: 3.0,
    Alexander_Barboza: 2.0,
    Vitinho: 2.5,
    Allan: 5.0,
    Danilo: 9.0,
    Alex_Telles: 3.0,
    Montoro: 7.5,
    Arthur_Cabral: 7.5,
    Artur: 5.0,
    Jordan_Barrera: 5.5,
    Matheus_Martins: 5.0,
    Martín_Anselmi: 5.5,
  },
  {
    partida: "Vasco (F)",
    data: "08/02/2026",
    resultado: "2 x 0",
    Léo_Linck: 3.0,
    Justino: 4.5,
    Bastos: 5.0,
    Alexander_Barboza: 7.5,
    Kadu: 5.5,
    Marquinhos: 2.0,
    Jordan_Barrera: 5.5,
    Gabriel_Abdias: 5.0,
    Matheus_Martins: 3.5,
    Nathan_Fernandes: 3.5,
    Kadir_Barría: 5.5,
    Bernardo_Valim: 3.5,
    Kauan_Toledo: 5.5,
    Arthur_Izaque: 4.5,
    Caio_Valle: 5.0,
    Arthur_Novaes: 5.0,
    Martín_Anselmi: 5.5,
  },
  {
    partida: "Fluminense",
    data: "12/02/2026",
    resultado: "Desconhecido",
    Neto: 1.0,
    Ythallo: 4.0,
    Newton: 2.0,
    Alexander_Barboza: 4.5,
    Vitinho: 3.0,
    Allan: 5.0,
    Danilo: 6.5,
    Alex_Telles: 3.0,
    Artur: 2.0,
    Montoro: 6.0,
    Arthur_Cabral: 4.0,
    Jordan_Barrera: 5.0,
    Nathan_Fernandes: 3.5,
    Matheus_Martins: 4.0,
    Lucas_Villalba: 5.5,
    Kadir_Barría: 5.5,
    Martín_Anselmi: 4.0,
  },
  {
    partida: "Flamengo (C)",
    data: "15/02/2026",
    resultado: "1 x 2",
    Neto: 0.0,
    Vitinho: 6.0,
    Bastos: 6.5,
    Alexander_Barboza: 7.5,
    Lucas_Villalba: 7.0,
    Newton: 6.5,
    Danilo: 5.0,
    Alex_Telles: 6.5,
    Jordan_Barrera: 7.0,
    Montoro: 6.0,
    Matheus_Martins: 5.0,
    Arthur_Novaes: 6.5,
    Artur: 4.0,
    Arthur_Cabral: 4.0,
    Martín_Anselmi: 5.5,
  },
  {
    partida: "Boavista (F)",
    data: "21/02/2026",
    resultado: "2 x 1",
    Raul: 6.0,
    Kadu: 5.5,
    Ythallo: 6.5,
    Justino: 7.5,
    Lucas_Villalba: 5.5,
    Arthur_Novaes: 7.0,
    Edenílson: 6.5,
    Jhoan_Hernández: 6.5,
    Caio_Valle: 6.0,
    Artur: 7.5,
    Nathan_Fernandes: 6.0,
    Gabriel_Abdias: 5.5,
    Kauan_Toledo: 5.5,
    Arthur_Izaque: 5.5,
    Bernardo_Valim: 5.5,
    Kadir_Barría: 5.5,
    Martín_Anselmi: 6.5,
  },
  {
    partida: "Nacional (C)",
    data: "25/02/2026",
    resultado: "2 x 1",
    Léo_Linck: 6.5,
    Mateo_Ponte: 3.0,
    Bastos: 6.5,
    Alexander_Barboza: 5.0,
    Vitinho: 7.5,
    Newton: 3.5,
    Danilo: 7.5,
    Alex_Telles: 7.0,
    Jordan_Barrera: 4.0,
    Montoro: 4.5,
    Matheus_Martins: 4.0,
    Artur: 4.0,
    Arthur_Cabral: 5.0,
    Justino: 5.5,
    Joaquín_Correa: 4.5,
    Martín_Anselmi: 5.5,
  },
  {
    partida: "Boavista (C)",
    data: "28/02/2026",
    resultado: "2 x 1",
    Raul: 5.0,
    Kadu: 5.0,
    Ythallo: 5.0,
    Justino: 5.0,
    Gabriel_Abdias: 5.0,
    Arthur_Novaes: 6.0,
    Edenílson: 5.5,
    Artur: 5.0,
    Joaquín_Correa: 5.0,
    Arthur_Cabral: 4.0,
    Lucas_Villalba: 5.0,
    Nathan_Fernandes: 5.0,
    Jordan_Barrera: 5.0,
    Montoro: 5.0,
    Martín_Anselmi: 5.0,
  },
  {
    partida: "Barcelona (F)",
    data: "03/03/2026",
    resultado: "2 x 1",
    Léo_Linck: 1.0,
    Mateo_Ponte: 4.5,
    Bastos: 7.5,
    Alexander_Barboza: 5.5,
    Vitinho: 6.5,
    Newton: 5.5,
    Danilo: 6.0,
    Alex_Telles: 6.0,
    Jordan_Barrera: 6.5,
    Montoro: 5.0,
    Matheus_Martins: 7.5,
    Lucas_Villalba: 6.0,
    Arthur_Cabral: 5.5,
    Martín_Anselmi: 5.5,
  },
  {
    partida: "Bangu (C)",
    data: "07/03/2026",
    resultado: "2 x 1",
    Raul: 6.5,
    Kadu: 5.5,
    Ythallo: 5.0,
    Justino: 6.5,
    Lucas_Villalba: 6.5,
    Arthur_Novaes: 5.0,
    Edenílson: 7.5,
    Nathan_Fernandes: 4.0,
    Caio_Valle: 8.0,
    Joaquín_Correa: 7.0,
    Arthur_Cabral: 6.5,
    Marquinhos: 5.0,
    Jhoan_Hernández: 5.0,
    Arthur_Izaque: 5.0,
    Martín_Anselmi: 6.5,
  },
  {
    partida: "Barcelona (F)",
    data: "10/03/2026",
    resultado: "0 x 1",
    Mateo_Ponte: 1.5,
    Bastos: 5.0,
    Alexander_Barboza: 4.0,
    Vitinho: 3.0,
    Newton: 4.5,
    Danilo: 5.0,
    Alex_Telles: 3.0,
    Jordan_Barrera: 3.5,
    Montoro: 2.0,
    Matheus_Martins: 6.5,
    Joaquín_Correa: 3.0,
    Arthur_Cabral: 5.5,
    Artur: 5.0,
    Caio_Valle: 5.0,
    Nathan_Fernandes: 3.5,
    Martín_Anselmi: 1.0,
  },
  {
    partida: "Flamengo (C)",
    data: "14/03/2026",
    resultado: "0 x 3",
    Raul: 4.0,
    Vitinho: 4.5,
    Bastos: 5.0,
    Alexander_Barboza: 0.0,
    Alex_Telles: 1.5,
    Allan: 3.0,
    Cristian_Medina: 6.0,
    Danilo: 5.0,
    Matheus_Martins: 4.0,
    Jordan_Barrera: 4.0,
    Arthur_Cabral: 1.0,
    Ferraresi: 5.5,
    Newton: 4.5,
    Mateo_Ponte: 5.0,
    Júnior_Santos: 5.0,
    Martín_Anselmi: 0.5,
  },
  {
    partida: "Palmeiras (F)",
    data: "18/03/2026",
    resultado: "2 x 1",
    Raul: 4.5,
    Vitinho: 3.0,
    Bastos: 5.0,
    Ferraresi: 5.0,
    Alex_Telles: 5.0,
    Danilo: 7.0,
    Cristian_Medina: 1.0,
    Jordan_Barrera: 4.0,
    Montoro: 4.0,
    Matheus_Martins: 4.5,
    Júnior_Santos: 4.5,
    Santiago_Rodríguez: 6.5,
    Lucas_Villalba: 5.5,
    Justino: 6.5,
    Artur: 5.0,
    Joaquín_Correa: 5.0,
    Martín_Anselmi: 5.0,
  },
  {
    partida: "Red Bull Bragantino (F)",
    data: "21/03/2026",
    resultado: "1 x 2",
    Raul: 10.0,
    Mateo_Ponte: 4.0,
    Ferraresi: 6.5,
    Alexander_Barboza: 8.5,
    Alex_Telles: 5.5,
    Danilo: 8.5,
    Santiago_Rodríguez: 5.5,
    Montoro: 6.0,
    Matheus_Martins: 4.5,
    Joaquín_Correa: 5.0,
    Júnior_Santos: 4.5,
    Vitinho: 6.5,
    Allan: 5.5,
    Lucas_Villalba: 5.5,
    Justino: 6.5,
    Edenílson: 5.0,
    Martín_Anselmi: 6.0,
  },
  {
    partida: "Athletico (F)",
    data: "29/03/2026",
    resultado: "4 x 1",
    Raul: 1.5,
    Vitinho: 2.0,
    Bastos: 2.5,
    Alexander_Barboza: 1.0,
    Alex_Telles: 3.0,
    Edenílson: 5.5,
    Cristian_Medina: 4.0,
    Santiago_Rodríguez: 3.0,
    Montoro: 5.0,
    Matheus_Martins: 3.0,
    Arthur_Cabral: 1.0,
    Lucas_Villalba: 3.5,
    Júnior_Santos: 5.0,
    Rodrigo_Bellão: 3.0,
  },
  {
    partida: "Mirassol (C)",
    data: "01/04/2026",
    resultado: "3x2",
    Raul: 6.5,
    Vitinho: 7.0,
    Bastos: 5.5,
    Justino: 8.0,
    Alex_Telles: 7.5,
    Allan: 7.0,
    Cristian_Medina: 5.5,
    Edenílson: 8.0,
    Júnior_Santos: 7.5,
    Santiago_Rodríguez: 6.0,
    Arthur_Cabral: 7.5,
    Caio_Roque: 5.5,
    Jordan_Barrera: 5.5,
    Montoro: 5.0,
    Matheus_Martins: 6.5,
    Ferraresi: 5.5,
    Rodrigo_Bellão: 7.0,
  },
  {
    partida: "Vasco (F)",
    data: "04/04/2026",
    resultado: "2 x 1",
    Raul: 6.0,
    Vitinho: 7.0,
    Ferraresi: 8.0,
    Alexander_Barboza: 8.0,
    Alex_Telles: 6.5,
    Allan: 7.0,
    Edenílson: 5.5,
    Danilo: 6.5,
    Júnior_Santos: 6.0,
    Matheus_Martins: 9.0,
    Arthur_Cabral: 7.0,
    Caio_Roque: 7.0,
    Lucas_Villalba: 8.5,
    Montoro: 5.0,
    Kadir_Barría: 5.5,
    Rodrigo_Bellão: 8.0,
  },
  {
    partida: "Caracas (C)",
    data: "09/04/2026",
    resultado: "1 x 1",
    Raul: 5.5,
    Vitinho: 3.0,
    Bastos: 4.0,
    Alexander_Barboza: 6.5,
    Caio_Roque: 4.5,
    Allan: 5.5,
    Danilo: 6.0,
    Santiago_Rodríguez: 5.0,
    Montoro: 5.5,
    Júnior_Santos: 4.5,
    Matheus_Martins: 5.0,
    Arthur_Cabral: 6.5,
    Mateo_Ponte: 5.5,
    Jordan_Barrera: 4.0,
    Jhoan_Hernández: 5.0,
    Kadir_Barría: 5.5,
    Franclim_Carvalho: 5.0,
  },
  {
    partida: "Coritiba",
    data: "12/04/2026",
    resultado: "2x2",
    Raul: 4.5,
    Vitinho: 6.5,
    Bastos: 3.0,
    Alexander_Barboza: 5.5,
    Jhoan_Hernández: 4.5,
    Danilo: 7.5,
    Cristian_Medina: 5.5,
    Santiago_Rodríguez: 3.0,
    Montoro: 4.5,
    Jordan_Barrera: 4.0,
    Arthur_Cabral: 7.0,
    Edenílson: 6.0,
    Lucas_Villalba: 6.0,
    Caio_Roque: 6.0,
    Matheus_Martins: 4.5,
    Chris_Ramos: 2.0,
    Franclim_Carvalho: 3.0,
  },
  {
    partida: "Chapecoense (C)",
    data: "18/04/2026",
    resultado: "3 x 0",
    Neto: 6.5,
    Vitinho: 6.5,
    Ferraresi: 7.5,
    Alexander_Barboza: 7.5,
    Alex_Telles: 7.0,
    Cristian_Medina: 7.5,
    Danilo: 8.0,
    Edenílson: 9.0,
    Júnior_Santos: 5.0,
    Matheus_Martins: 10.0,
    Arthur_Cabral: 5.0,
    Joaquín_Correa: 6.0,
    Jordan_Barrera: 5.5,
    Kadir_Barría: 5.5,
    Allan: 5.5,
    Franclim_Carvalho: 8.0,
  },
  {
    partida: "Chapecoense (C)",
    data: "21/04/2026",
    resultado: "1 x 0",
    Neto: 6.0,
    Vitinho: 7.0,
    Ferraresi: 7.5,
    Bastos: 7.0,
    Caio_Roque: 2.0,
    Allan: 5.5,
    Danilo: 6.0,
    Montoro: 8.5,
    Matheus_Martins: 5.5,
    Júnior_Santos: 5.0,
    Kadir_Barría: 5.5,
    Alex_Telles: 8.0,
    Arthur_Cabral: 5.0,
    Cristian_Medina: 6.5,
    Edenílson: 6.0,
    Joaquín_Correa: 5.0,
    Franclim_Carvalho: 6.5,
  },
  {
    partida: "Internacional (C)",
    data: "25/04/2026",
    resultado: "2x2",
    Neto: 3.0,
    Vitinho: 5.0,
    Ferraresi: 6.5,
    Alexander_Barboza: 2.0,
    Alex_Telles: 5.5,
    Cristian_Medina: 7.0,
    Danilo: 8.0,
    Edenílson: 6.0,
    Júnior_Santos: 4.0,
    Matheus_Martins: 5.5,
    Arthur_Cabral: 4.5,
    Mateo_Ponte: 6.0,
    Kadir_Barría: 6.5,
    Montoro: 5.5,
    Joaquín_Correa: 3.0,
    Allan: 5.5,
    Franclim_Carvalho: 4.0,
  },
  {
    partida: "Independiente Petrolero (C)",
    data: "28/04/2026",
    resultado: "3 x 0",
    Neto: 5.0,
    Mateo_Ponte: 8.0,
    Bastos: 5.5,
    Alexander_Barboza: 7.0,
    Alex_Telles: 7.5,
    Allan: 5.5,
    Cristian_Medina: 7.0,
    Edenílson: 6.0,
    Montoro: 7.5,
    Kadir_Barría: 7.5,
    Arthur_Cabral: 5.0,
    Santiago_Rodríguez: 6.5,
    Joaquín_Correa: 5.0,
    Chris_Ramos: 6.0,
    Marçal: 6.5,
    Newton: 7.0,
    Franclim_Carvalho: 6.5,
  },
  {
    partida: "Remo (C)",
    data: "02/05/2026",
    resultado: "1x2",
    Neto: 7.0,
    Vitinho: 4.5,
    Ferraresi: 6.5,
    Bastos: 3.0,
    Alex_Telles: 6.5,
    Cristian_Medina: 6.5,
    Danilo: 5.5,
    Montoro: 4.0,
    Matheus_Martins: 4.5,
    Kadir_Barría: 5.5,
    Arthur_Cabral: 3.5,
    Edenílson: 5.0,
    Allan: 4.0,
    Marçal: 5.0,
    Joaquín_Correa: 4.0,
    Franclim_Carvalho: 2.0,
  },
  {
    partida: "Atlético-MG (F)",
    data: "10/05/2026",
    resultado: "1x1",
    Neto: 7.5,
    Mateo_Ponte: 6.0,
    Ferraresi: 5.5,
    Alexander_Barboza: 6.5,
    Alex_Telles: 5.5,
    Newton: 3.0,
    Cristian_Medina: 5.5,
    Danilo: 4.5,
    Edenílson: 4.0,
    Matheus_Martins: 4.5,
    Arthur_Cabral: 7.0,
    Kadir_Barría: 5.5,
    Marçal: 6.5,
    Montoro: 5.5,
    Jordan_Barrera: 4.5,
    Franclim_Carvalho: 5.0,
  },
  {
    partida: "Chapecoense (F)",
    data: "14/05/2026",
    resultado: "2 x 0",
    Neto: 0.0,
    Vitinho: 0.5,
    Bastos: 0.0,
    Alexander_Barboza: 0.0,
    Marçal: 1.0,
    Danilo: 3.0,
    Cristian_Medina: 4.0,
    Edenílson: 1.0,
    Montoro: 4.5,
    Júnior_Santos: 0.0,
    Arthur_Cabral: 1.0,
    Kadir_Barría: 1.5,
    Alex_Telles: 5.0,
    Santiago_Rodríguez: 3.0,
    Joaquín_Correa: 1.5,
    Lucas_Villalba: 2.5,
    Franclim_Carvalho: 0.0,
  },
  {
    partida: "Corinthians (C)",
    data: "17/05/2026",
    resultado: "3 x 1",
    Neto: 6.5,
    Mateo_Ponte: 6.5,
    Ferraresi: 8.5,
    Alexander_Barboza: 9.0,
    Alex_Telles: 7.0,
    Huguinho: 6.5,
    Cristian_Medina: 6.5,
    Montoro: 7.5,
    Lucas_Villalba: 8.5,
    Kadir_Barría: 5.5,
    Arthur_Cabral: 10.0,
    Kauan_Toledo: 8.5,
    Vitinho: 6.0,
    Edenílson: 5.5,
    Justino: 6.0,
    Santiago_Rodríguez: 6.0,
    Franclim_Carvalho: 7.5,
  },
  {
    partida: "Independiente Petrolero (F)",
    data: "20/05/2026",
    resultado: "0 x 3",
    Neto: 6.0,
    Mateo_Ponte: 6.5,
    Ferraresi: 7.0,
    Alexander_Barboza: 7.0,
    Alex_Telles: 6.5,
    Huguinho: 7.5,
    Cristian_Medina: 8.0,
    Montoro: 7.5,
    Lucas_Villalba: 7.0,
    Kauan_Toledo: 6.0,
    Arthur_Cabral: 6.5,
    Caio_Valle: 6.0,
    Chris_Ramos: 6.5,
    Santiago_Rodríguez: 6.5,
    Jordan_Barrera: 7.0,
    Joaquín_Correa: 7.0,
    Franclim_Carvalho: 7.0,
  },
  {
    partida: "São Paulo (F)",
    data: "23/05/2026",
    resultado: "1 x 1",
    Neto: 2.0,
    Vitinho: 6.0,
    Ferraresi: 7.5,
    Justino: 7.0,
    Marçal: 5.5,
    Huguinho: 4.0,
    Santiago_Rodríguez: 6.5,
    Montoro: 4.0,
    Lucas_Villalba: 4.0,
    Kauan_Toledo: 4.0,
    Arthur_Cabral: 5.5,
    Kadir_Barría: 6.0,
    Edenílson: 6.5,
    Jordan_Barrera: 8.0,
    Joaquín_Correa: 3.5,
    Chris_Ramos: 3.0,
    Franclim_Carvalho: 5.0,
  },
  {
    partida: "Caracas (F)",
    data: "27/05/2026",
    resultado: "1 x 3",
    Raul: 5.5,
    Vitinho: 4.0,
    Ythallo: 5.5,
    Justino: 5.0,
    Marçal: 5.0,
    Wallace_Davi: 3.0,
    Santiago_Rodríguez: 6.0,
    Edenílson: 5.0,
    Jordan_Barrera: 4.5,
    Joaquín_Correa: 7.5,
    Chris_Ramos: 5.5,
    Kadu: 6.0,
    Cristian_Medina: 6.5,
    Matheus_Martins: 6.5,
    Caio_Valle: 6.0,
    Kauan_Toledo: 7.5,
    Franclim_Carvalho: 7.0,
  },
  {
    partida: "Bahia (F)",
    data: "30/05/2026",
    resultado: "2 x 1",
    Neto: 0.0,
    Mateo_Ponte: 5.0,
    Ferraresi: 1.0,
    Justino: 6.0,
    Alex_Telles: 6.5,
    Huguinho: 7.0,
    Cristian_Medina: 6.5,
    Montoro: 6.5,
    Lucas_Villalba: 5.5,
    Kauan_Toledo: 5.5,
    Arthur_Cabral: 6.5,
    Raul: 3.0,
    Newton: 5.0,
    Santiago_Rodríguez: 5.0,
    Matheus_Martins: 5.0,
    Franclim_Carvalho: 6.5,
  },
];

// 3. Função exata do backend para calcular variações (deltas) com consistência
const recalcularVariacoes = (db, startIndex) => {
  for (let i = Math.max(0, startIndex); i < db.historicoRodadas.length; i++) {
    const rodadaAtual = db.historicoRodadas[i];
    const rodadaAnterior = i > 0 ? db.historicoRodadas[i - 1] : {};

    db.jogadoresDisponiveis.forEach((jogador) => {
      if (rodadaAtual[jogador.id] !== undefined) {
        const notaAtualNum = parseFloat(rodadaAtual[jogador.id]);
        const notaAnteriorNum =
          rodadaAnterior[jogador.id] !== undefined
            ? parseFloat(rodadaAnterior[jogador.id])
            : notaAtualNum;
        let variacao = notaAtualNum - notaAnteriorNum;

        if (variacao > 0)
          rodadaAtual[`${jogador.id}_variacao`] = `+${variacao.toFixed(1)}`;
        else if (variacao < 0)
          rodadaAtual[`${jogador.id}_variacao`] = variacao.toFixed(1);
        else rodadaAtual[`${jogador.id}_variacao`] = "0.0";
      }
    });
  }
};

// 4. Estrutura final e salvamento
const db = {
  jogadoresDisponiveis: jogadores,
  historicoRodadas: historico,
};

recalcularVariacoes(db, 0); // Dispara os cálculos das 36 rodadas sequencialmente

fs.writeFileSync(dbPath, JSON.stringify(db, null, 2), "utf-8");
console.log(
  "✅ Banco de dados 'database.json' populado com sucesso com os 36 jogos!",
);
